a=int(input("numarul de oua care il face prima gaina intr-o zi ="))
b=int(input("numarul de oua care il face a doua gaina intr-o zi ="))
c=int(input("numarul de oua care il face a treia gaina intr-o zi ="))
d=int(input("numarul de oua care il face a patra gaina intr-o zi ="))
print("intr-o saptamina gainile vor face in total ",7*(a+b+c+d)," de oua")
